[package]
name = "varmint"
version = "0.1.0"
edition = "2024"

[dependencies]
applevisor = "1.0"
coreaudio-rs = "0.14.2"
crossterm = "0.29.0"
num_enum = "0.7.6"
objc2 = "0.6.4"
objc2-app-kit = "0.3.2"
objc2-foundation = "0.3.2"
pollster = "0.4.0"
rtrb = "0.3.4"
rutabaga_gfx = { git = "https://github.com/containers/libkrun", package = "krun-rutabaga-gfx", features = [
    "virgl_renderer",
    "virgl_renderer_next",
] }
vmnet = "0.5.1"
wgpu = "29.0.3"
winit = "0.30.13"
zerocopy = { version = "0.8.50", features = ["derive"] }
