schema_version = 1

[runtime]
minimum_macos = "26.0"
architectures = ["arm64"]
dylibs = [
  "libvirglrenderer.1.dylib",
  "libepoxy.0.dylib",
  "libEGL.dylib",
  "libGLESv2.dylib",
  "libMoltenVK.dylib",
  "libdxmt-native.dylib",
]

[dependencies.angle]
repository = "https://github.com/utmapp/WebKit.git"
commit = "ed78ab6e1a37f4f11583a0bd038f22ec91f3ff10"

[dependencies.epoxy]
repository = "https://github.com/utmapp/libepoxy.git"
commit = "5014658f79e4d6872a1ad6754da9098ccd9d4fc5"

[dependencies.moltenvk]
repository = "https://github.com/utmapp/MoltenVK.git"
commit = "ef1c5461774f5fbd224ddcfd91fd2c0ea23f0384"
version = "1.4.2-utm-geometry"

[dependencies.virglrenderer]
repository = "https://github.com/utmapp/virglrenderer.git"
commit = "482f9d8b8c2d2288efa10a027116216909d2c226"

[dependencies.dxmt]
repository = "https://github.com/utmapp/dxmt.git"
commit = "bcdcf6da89af6c9fedeb2fc92b4367b23d5d6ed6"
