#!/bin/sh
set -e

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "${1:-}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec "$(command -v fsck)" /sbin/fsck
copy_exec "$(command -v e2fsck)" /sbin/e2fsck
ln -sf e2fsck "${DESTDIR}/sbin/fsck.ext4"
