use crate::virtio::input::keys::*;
use applevisor::prelude::*;

pub fn reg_from_rt(rt: u64) -> Option<Reg> {
    match rt {
        0 => Some(Reg::X0),
        1 => Some(Reg::X1),
        2 => Some(Reg::X2),
        3 => Some(Reg::X3),
        4 => Some(Reg::X4),
        5 => Some(Reg::X5),
        6 => Some(Reg::X6),
        7 => Some(Reg::X7),
        8 => Some(Reg::X8),
        9 => Some(Reg::X9),
        10 => Some(Reg::X10),
        11 => Some(Reg::X11),
        12 => Some(Reg::X12),
        13 => Some(Reg::X13),
        14 => Some(Reg::X14),
        15 => Some(Reg::X15),
        16 => Some(Reg::X16),
        17 => Some(Reg::X17),
        18 => Some(Reg::X18),
        19 => Some(Reg::X19),
        20 => Some(Reg::X20),
        21 => Some(Reg::X21),
        22 => Some(Reg::X22),
        23 => Some(Reg::X23),
        24 => Some(Reg::X24),
        25 => Some(Reg::X25),
        26 => Some(Reg::X26),
        27 => Some(Reg::X27),
        28 => Some(Reg::X28),
        29 => Some(Reg::X29),
        30 => Some(Reg::X30),
        31 => None, // XZR/WZR: zero register, not a real stored register
        _ => None,
    }
}

pub fn set_rt(vcpu: &Vcpu, rt: u64, value: u64) -> Result<()> {
    if let Some(reg) = reg_from_rt(rt) {
        vcpu.set_reg(reg, value)?;
    }

    Ok(())
}

pub fn get_rt(vcpu: &Vcpu, rt: u64) -> Result<u64> {
    Ok(match reg_from_rt(rt) {
        Some(reg) => vcpu.get_reg(reg)?,
        None => 0, // XZR/WZR
    })
}

pub fn winit_to_linux_key(key: winit::keyboard::KeyCode) -> Option<u16> {
    use winit::keyboard::KeyCode::*;
    Some(match key {
        Escape => KEY_ESC,
        Digit1 => KEY_1,
        Digit2 => KEY_2,
        Digit3 => KEY_3,
        Digit4 => KEY_4,
        Digit5 => KEY_5,
        Digit6 => KEY_6,
        Digit7 => KEY_7,
        Digit8 => KEY_8,
        Digit9 => KEY_9,
        Digit0 => KEY_0,
        Minus => KEY_MINUS,
        Equal => KEY_EQUAL,
        Backspace => KEY_BACKSPACE,
        Tab => KEY_TAB,
        KeyQ => KEY_Q,
        KeyW => KEY_W,
        KeyE => KEY_E,
        KeyR => KEY_R,
        KeyT => KEY_T,
        KeyY => KEY_Y,
        KeyU => KEY_U,
        KeyI => KEY_I,
        KeyO => KEY_O,
        KeyP => KEY_P,
        BracketLeft => KEY_LEFTBRACE,
        BracketRight => KEY_RIGHTBRACE,
        Enter => KEY_ENTER,
        ControlLeft => KEY_LEFTCTRL,
        KeyA => KEY_A,
        KeyS => KEY_S,
        KeyD => KEY_D,
        KeyF => KEY_F,
        KeyG => KEY_G,
        KeyH => KEY_H,
        KeyJ => KEY_J,
        KeyK => KEY_K,
        KeyL => KEY_L,
        Semicolon => KEY_SEMICOLON,
        Quote => KEY_APOSTROPHE,
        Backquote => KEY_GRAVE,
        ShiftLeft => KEY_LEFTSHIFT,
        Backslash => KEY_BACKSLASH,
        KeyZ => KEY_Z,
        KeyX => KEY_X,
        KeyC => KEY_C,
        KeyV => KEY_V,
        KeyB => KEY_B,
        KeyN => KEY_N,
        KeyM => KEY_M,
        Comma => KEY_COMMA,
        Period => KEY_DOT,
        Slash => KEY_SLASH,
        ShiftRight => KEY_RIGHTSHIFT,
        AltLeft => KEY_LEFTALT,
        Space => KEY_SPACE,
        CapsLock => KEY_CAPSLOCK,
        F1 => KEY_F1,
        F2 => KEY_F2,
        F3 => KEY_F3,
        F4 => KEY_F4,
        F5 => KEY_F5,
        F6 => KEY_F6,
        F7 => KEY_F7,
        F8 => KEY_F8,
        F9 => KEY_F9,
        F10 => KEY_F10,
        F11 => KEY_F11,
        F12 => KEY_F12,
        NumLock => KEY_NUMLOCK,
        ScrollLock => KEY_SCROLLLOCK,
        Numpad7 => KEY_KP7,
        Numpad8 => KEY_KP8,
        Numpad9 => KEY_KP9,
        NumpadSubtract => KEY_KPMINUS,
        Numpad4 => KEY_KP4,
        Numpad5 => KEY_KP5,
        Numpad6 => KEY_KP6,
        NumpadAdd => KEY_KPPLUS,
        Numpad1 => KEY_KP1,
        Numpad2 => KEY_KP2,
        Numpad3 => KEY_KP3,
        Numpad0 => KEY_KP0,
        NumpadDecimal => KEY_KPDOT,
        NumpadEnter => KEY_KPENTER,
        NumpadDivide => KEY_KPSLASH,
        NumpadMultiply => KEY_KPASTERISK,
        ControlRight => KEY_RIGHTCTRL,
        AltRight => KEY_RIGHTALT,
        Home => KEY_HOME,
        ArrowUp => KEY_UP,
        PageUp => KEY_PAGEUP,
        ArrowLeft => KEY_LEFT,
        ArrowRight => KEY_RIGHT,
        End => KEY_END,
        ArrowDown => KEY_DOWN,
        PageDown => KEY_PAGEDOWN,
        Insert => KEY_INSERT,
        Delete => KEY_DELETE,
        _ => return None,
    })
}
